### ISSUE TITLE
不能兼容loliserver服务端

### ISSUE THREAD

**Issue by zfms4188** [yuoft/Endless#1]
启动时报错并崩溃,以下是日志
https://pastebin.com/k8QdTG9Z

**Comment by yuoft** [comment]
你服务端用forge吗？版本是多少？我看报错是没找到某个类。我没接触过服务端。

**Comment by zfms4188** [comment]
https://github.com/Luohuayu/CatServer/tree/1.16.5
forge+bukkit混合端

**Comment by yuoft** [comment]
我看了一下，forge和mcp版本不一样。不知道是不是这个的原因，你本地联机没问题的话，可能就是因为版本问题。
我今晚不方便用电脑，后续问题我明天回复，不好意思了。

**Comment by zfms4188** [comment]
> 我看了一下，forge和mcp版本不一样。不知道是不是这个的原因，你本地联机没问题的话，可能就是因为版本问题。 我今晚不方便用电脑，后续问题我明天回复，不好意思了。

彳亍,明天你再看看,要不行的话,我再去服务端那边反馈一下

**Comment by cnlimiter** [comment]
双端没有加判定吧

**Comment by cnlimiter** [comment]
我已经修复了，等会merge一下

**Comment by zfms4188** [comment]
什么时候更新修复版本喃

**Comment by yuoft** [comment]
> 什么时候更新修复版本喃

得等两天，我在添加新内容时碰到了一些bug。

**Comment by zfms4188** [comment]
> > 什么时候更新修复版本喃
> 
> 得等两天，我在添加新内容时碰到了一些bug。

好的,加油
