### ISSUE TITLE
Draconic Infinity Armor Death

### ISSUE THREAD

**Issue by IamRyan30** [yuoft/Endless#10]
Mc: 1.16.5
Forge. 36.2.33
Endless Fake: Endless-1.16.5-1.3.0.1.jar
Draconic Evolution: Draconic-Evolution-1.16.5-3.0.26.459-universal.jar
Brandon Core: BrandonsCore-1.16.5-3.0.14.247-universal.jar

Hi. First, my apologies if this github is not meant for international bug reports. Second, I've discovered an issue related to Draconic Evolution. While you're on a Chaos Island, you can die in the Infinity Armor. After dying, you can't respawn. The only fix will be to go back to the title screen and re-join your map. After that, you'll be in the same spot where you died previously, but you'll not be dead. The log file doesn't say anything about this. There's just [this](https://gist.github.com/IamRyan30/aced8f8e320850d8eab9cb7478f50607).

你好。 首先，如果此 github 不适用于国际错误报告，我深表歉意。 其次，我发现了一个与龙进化有关的问题。 当你在混沌岛上时，你可以穿着 Infinity Armor 死去。 死后无法重生。 唯一的解决办法是返回标题屏幕并重新加入您的地图。 在那之后，你会回到你之前死去的地方，但你不会死。 日志文件没有说明这一点。 只有这个。

**Comment by yuoft** [comment]
OK, I will try to solve this problem.

好的，我会尝试解决这个问题

**Comment by yuoft** [comment]
> OK, I will try to solve this problem.
> 
> 好的，我会尝试解决这个问题

好的，我会尝试解决这个问题
If I can find the problem

**Comment by yuoft** [comment]
很抱歉，我目前没有找到问题在哪，也许你可以在【龙之研究】作者哪里反馈试试。

I'm sorry, but I haven't found the problem at present. Maybe you can give feedback from the author of [Draconic Evolution]

**Comment by IamRyan30** [comment]
Sorry for the long response time. I.. actually - I think the issue is related to the Infinity Bow :/ Here's a [video](https://vimeo.com/manage/videos/723443491/privacy),

**Comment by IamRyan30** [comment]
> Sorry for the long response time. I.. actually - I think the issue is related to the Infinity Bow :/ Here's a [video](https://vimeo.com/manage/videos/723443491/privacy),

The Guardian might have a thorns effect on it? If so, can you disable it? I doubt draconic has a config for that.

**Comment by IamRyan30** [comment]
> Sorry for the long response time. I.. actually - I think the issue is related to the Infinity Bow :/ Here's a [video](https://vimeo.com/manage/videos/723443491/privacy),

Yep, I can confirm it. I tried to fight the Chaos Guardian with another armor, with the Infinity Bow. The issue was still there.

**Comment by IamRyan30** [comment]
Might be something related to [this](https://github.com/yuoft/Endless/blob/master/src/main/java/com/yuo/endless/Entity/InfinityArrowEntity.java#L87)..?

**Comment by yuoft** [comment]
Maybe I'll try

**Comment by yuoft** [comment]
在1.3.1版本中，这个问题可能已经不存在了。至少我完整的击杀了混沌守卫，并且没有出现问题。

**Comment by IamRyan30** [comment]
> 在1.3.1版本中，这个问题可能已经不存在了。至少我完整的击杀了混沌守卫，并且没有出现问题。

I'll give it a look. Thanks a lot.

我来看看。非常感谢。

**Comment by IamRyan30** [comment]
Ok, I just checked and it looks like the Bow issue, was fixed. Also, the idea of instantly breaking the DE Crystals was brilliant. The fact that it also is configurable, is amazing.

好的，我剛剛檢查了一下，看起來弓的問題已經解決了。此外，立即打破 DE 水晶的想法非常棒。它也是可配置的這一事實令人驚嘆。
