### ISSUE TITLE
Error During the common_startup event phase

### ISSUE THREAD

**Issue by michaelng1129** [yuoft/Endless#13]
Forge: 36.2.34
mod版本：1.3.3及其打后
Java版本: 1.8.0_333

错误信息：
Exception message: java.lang.NullPointerException

crashreport:
1.3.3
[crash-2022-07-10_14.17.02-fml.txt](https://github.com/yuoft/Endless/files/9078581/crash-2022-07-10_14.17.02-fml.txt)
1.3.4
[crash-2022-07-10_14.10.57-fml.txt](https://github.com/yuoft/Endless/files/9078578/crash-2022-07-10_14.10.57-fml.txt)
1.3.5
[crash-2022-07-10_12.43.08-fml.txt](https://github.com/yuoft/Endless/files/9078580/crash-2022-07-10_12.43.08-fml.txt)

**Comment by michaelng1129** [comment]
经测试
与MrCrayfish mod系列发生冲突
主要冲突mod为该系列前置obfuscate
有可能的解决方法
https://forums.minecraftforge.net/topic/109586-error-during-the-common_setup-event-phase/
![image](https://user-images.githubusercontent.com/43681657/178135242-2e8f649d-3f26-49d7-abe6-3d2b383ccbff.png)

**Comment by yuoft** [comment]
我无法找到这个错误是如何产生的

**Comment by michaelng1129** [comment]
1.3.3之前都是正常的 这个版本开始之后是不是改动了什么导致的

**Comment by yuoft** [comment]
错误行数在加的热力联动哪里，但是加上热力模组并不会报错

**Comment by michaelng1129** [comment]
> 

我把Thermal Series移除 它就能正常启动了 是不是联动部分有可能有问题啊

**Comment by yuoft** [comment]
你说的这是一个系列啊，具体是哪个呢？我加了热力基本和热力农业，是能正常进入游戏的

**Comment by michaelng1129** [comment]
> 你说的这是一个系列啊，具体是哪个呢？我加了热力基本和热力农业，是能正常进入游戏的

就那個最基础的那个 我只要把这个拔了 就能进去了 
![image](https://user-images.githubusercontent.com/43681657/178207031-17b419e9-6c29-4fd3-bf45-359164fb6eec.png)

**Comment by yuoft** [comment]
https://www.mcmod.cn/class/425.html
基础模组是个啊，你那是哪里来的？

**Comment by michaelng1129** [comment]
https://www.mcmod.cn/class/3824.html
这个

**Comment by yuoft** [comment]
额，这是一个模组集合啊，你去哪里下了一个模组文件？

**Comment by michaelng1129** [comment]
直接curse下载的 他好像1.14之后就合并成这样了

**Comment by michaelng1129** [comment]
我知道了 他们之前是合在一起的 不知道什么时候又拆开了 我这个包是上上个月组的 我说我怎么老觉得少东西 
![image](https://user-images.githubusercontent.com/43681657/178210845-c927ca32-b85f-4283-87b1-6e961784a666.png)

**Comment by yuoft** [comment]
去掉之后能正常游戏不？

**Comment by michaelng1129** [comment]
> 去掉之后能正常游戏不？

去掉就能正常游戏 我刚刚也测试了 1.3.3打后的版本 我这个包 只要装上热力基本 有没有附属都会发生错误
