### ISSUE TITLE
小建议喃

### ISSUE THREAD

**Issue by zfms4188** [yuoft/Endless#3]
有没有一种可能 就是类似 无尽剑的右键范围伤害 啄颅剑的砍头掉率 什么的可以在配置文件修改范围或者关闭它.
在多人游戏的情景下 可能会对其他人有一定影响

**Comment by yuoft** [comment]
> 有没有一种可能 就是类似 无尽剑的右键范围伤害 啄颅剑的砍头掉率 什么的可以在配置文件修改范围或者关闭它。在多人游戏的情景下 可能会对其他人有一定影响

啄颅剑是必定掉落的，其它的可以考虑。

**Comment by zfms4188** [comment]
看见你在问配置文件的建议 简单喵两句
配置范围挖掘方块工具的黑名单 黑名单方块不会被采集
设置无尽镐是否可以破坏基岩
然后上面说的剑的攻击范围开关什么的
