### ISSUE TITLE
1.2.5kill @e指令清除无尽物品实体类掉落物bug

### ISSUE THREAD

**Issue by 6371peter** [yuoft/Endless#5]
Endless-1.16.5-1.2.5
Forge:36.2.35
在单人游戏以及多人游戏均会出现

复现步骤：
1.丢弃无尽物品实体类物品（寰宇支配之剑等）
2.用kill @e[type=item]清理
3.不去拾起之前丢弃的物品，在其下方放置漏斗
4.掉落物不会进入漏斗，但漏斗中将不断增加这种掉落物

用指令清理时会提示已清除掉落物，在混合服务端（mohist）中用kill @e[type=item]清理后物品将无法被拾起，但是仍会出现上述bug；在单人游戏以及forge服务端中用指令清理后仍可以正常拾起掉落物。

**Comment by 6371peter** [comment]
![2022-05-26_08 46 41](https://user-images.githubusercontent.com/64669376/170392508-1218e5da-a803-4c56-8874-0913b78708a5.png)
![2022-05-26_08 47 02](https://user-images.githubusercontent.com/64669376/170392527-ccaf0eb1-bc6c-43b7-81af-35f7054f38cb.png)

**Comment by yuoft** [comment]
好的，已知

**Comment by zfms4188** [comment]
使用指令给予 会多一件装备出来
