### ISSUE TITLE
无尽箱子问题

### ISSUE THREAD

**Issue by zfms4188** [yuoft/Endless#9]
使用创造模式打掉无尽箱子 会掉落为 压缩箱子  生存模式无此问题

**Comment by yuoft** [comment]
> 使用创造模式打掉无尽箱子 会掉落为 压缩箱子 生存模式无此问题

额！压缩箱子有问题吗？

**Comment by yuoft** [comment]
> 使用创造模式打掉无尽箱子 会掉落为 压缩箱子 生存模式无此问题

是在服务端？
